name: visuals_calendar
description: A modular Flutter Calendar package.
version: 0.0.3
homepage: https://github.com/williamskaug/visuals_calendar

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0